version: '3'

services:
  webapp: 
    build: .
    restart: always
    volumes:
      - ./:/data
    ports:
      - '5000:5000'
    environment:
      FLASK_APP: 'app.py'
      FLASK_ENV: 'development'
    depends_on:
      - redis
        
  redis:
    image: redis:4
    restart: always
    expose:
      - 6379
    volumes:
      - redisdata:/data

volumes:
  redisdata: